export const CATEGORIES_ACTION_TYPES = {
	FETCH_CATEGORIES_START: "category/SET_FETCH_CATEGORIES_START",
	FETCH_CATEGORIES_SUCCESS: "category/SET_FETCH_CATEGORIES_SUCCESS",
	FETCH_CATEGORIES_FAILED: "category/SET_FETCH_CATEGORIES_FAILED",
};
